### ISSUE TITLE
Customizable size

### ISSUE THREAD

**Issue by lexcaraig** [basst314/ngx-webcam#8]
It would be great if we can customize the size of the camera. Like responsive of onDemand.

**Comment by basst314** [comment]
Do you mean by putting the webcam component in a container with predefined size, or do you mean the user should be able to resize the webcam component at runtime?

**Comment by lexcaraig** [comment]
Well, i think the width and height should be responsive so anyone can just resize the container at runtime or not. :) Bec, I did some hook just to make it responsive.

Setting a fix size would be also nice.

**Comment by brayanmcz** [comment]
@rickdroio We're you able to get your camera to resize using the code you used above? 
I tried it and it did not work for me.

**Comment by sam-lex** [comment]
If you want to make it "responsive full screen", then this will work for you.  

Not sure about custom responsive solutions, you could tweak it by doing the calculations yourself if it's not too complicated.

```typescript
export class TakePictureComponent implements OnInit {
  private width: number;
  private height: number;

  @HostListener('window:resize', ['$event'])
  onResize(event?: Event) {
    const win = !!event ? (event.target as Window) : window;
    this.width = win.innerWidth;
    this.height = win.innerHeight;
  }

  constructor() {
    this.onResize();
  }
  // ...
}
```
```html
<div class="wrapper" (window:resize)="onResize($event)">
  <!-- Webcam -->
  <webcam [trigger]="triggerObservable"
      [width]="width"
      [height]="height"
      (imageCapture)="onImageCapture($event)">
  </webcam>

  <!-- Controls -->
</div>
```
```scss
.wrapper {
  display: flex;
  background: #383838;
  height: 100vh;
  align-items: center;
  justify-content: center;
  // inexplicable/unknown extra space is rendered, causing scrollbars to show up 
  overflow: hidden;
}
```
